module NoCommentsAnalyzer.Analyzer

open System
open System.IO
open FSharp.Analyzers.SDK
open FSharp.Compiler.Syntax
open FSharp.Compiler.Text

[<Literal>]
let CommentBannedCode = "NOCOMMENT001"

[<Literal>]
let SuppressionInUseCode = "NOCOMMENT002"

[<Literal>]
let InvalidConfigCode = "NOCOMMENT003"

[<Literal>]
let private MessageType = "NoComments"

let private generatedMarkers = [ "@generated"; "<auto-generated>"; "<auto-generated/>" ]

let private containsGeneratedMarker (text: string) =
    generatedMarkers
    |> List.exists (fun marker -> text.Contains(marker, StringComparison.OrdinalIgnoreCase))

let private commentBody (text: string) =
    if text.StartsWith "(*" then text.Substring 2
    else text.TrimStart '/'

let private pathForGlobs (config: Config.PolicyConfig) (fileName: string) =
    let fullPath =
        try
            Path.GetFullPath fileName
        with _ ->
            fileName

    match config.ConfigDirectory with
    | Some configDirectory ->
        let relative =
            try
                Path.GetRelativePath(configDirectory, fullPath)
            with _ ->
                fullPath

        relative.Replace('\\', '/')
    | None -> fullPath.Replace('\\', '/').TrimStart '/'

let private invalidConfigMessage (fileName: string) (reason: string) =
    { Type = MessageType
      Message = $"{Config.ConfigFileName} is invalid, so the baseline policy applies: {reason}"
      Code = InvalidConfigCode
      Severity = Severity.Error
      Range = Range.mkRange fileName (Position.mkPos 1 0) (Position.mkPos 1 0)
      Fixes = [] }

let private commentBannedMessage (comment: Detection.LogicalComment) =
    { Type = MessageType
      Message =
        "Code comments are banned by the no-comments policy; encode this knowledge in names, types, tests, docs, or commit messages."
      Code = CommentBannedCode
      Severity = Severity.Error
      Range = comment.Range
      Fixes = [] }

let private suppressionInUseMessage (comment: Detection.LogicalComment) =
    { Type = MessageType
      Message =
        "Analyzer suppression is an emergency escape hatch and every use is a bug to burn down; remove the directive and the comment it protects."
      Code = SuppressionInUseCode
      Severity = Severity.Warning
      Range = comment.Range
      Fixes = [] }

let analyze (fileName: string) (sourceText: ISourceText) (ast: ParsedInput) : Message list =
    let config = Config.load fileName

    let configMessages =
        match config.Error with
        | Some reason -> [ invalidConfigMessage fileName reason ]
        | None -> []

    let globPath = pathForGlobs config fileName

    if config.GeneratedGlobs |> List.exists (fun glob -> Glob.isMatch glob globPath) then
        configMessages
    else
        let fileComments = Detection.collect fileName sourceText ast

        let isHeaderComment (comment: Detection.LogicalComment) =
            match fileComments.FirstCodePos with
            | None -> true
            | Some firstCode -> Position.posLt comment.Range.Start firstCode

        let isGeneratedFile =
            fileComments.Comments
            |> List.exists (fun comment -> isHeaderComment comment && containsGeneratedMarker comment.Text)

        if isGeneratedFile then
            configMessages
        else
            let commentMessages =
                fileComments.Comments
                |> List.choose (fun comment ->
                    let body = (commentBody comment.Text).TrimStart()

                    let isSuppression =
                        body.StartsWith("fsharpanalyzer:", StringComparison.Ordinal)

                    let isDirective =
                        config.DirectivePrefixes
                        |> List.exists (fun prefix -> body.StartsWith(prefix, StringComparison.Ordinal))

                    if isSuppression then Some(suppressionInUseMessage comment)
                    elif isDirective then None
                    else Some(commentBannedMessage comment))

            configMessages @ commentMessages

[<Literal>]
let private AnalyzerName = "NoCommentsAnalyzer"

[<Literal>]
let private AnalyzerDescription =
    "Reports every code comment except machine-read directives, generated files, and shebangs."

[<CliAnalyzer(AnalyzerName, AnalyzerDescription)>]
let noCommentsCliAnalyzer: Analyzer<CliContext> =
    fun (context: CliContext) ->
        async { return analyze context.ParseFileResults.FileName context.SourceText context.ParseFileResults.ParseTree }

[<EditorAnalyzer(AnalyzerName, AnalyzerDescription)>]
let noCommentsEditorAnalyzer: Analyzer<EditorContext> =
    fun (context: EditorContext) ->
        async { return analyze context.ParseFileResults.FileName context.SourceText context.ParseFileResults.ParseTree }
